import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import logo from "/public/assets/logo.png";
import { Toaster } from "@/components/ui/sonner"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <header className="p-6">
          <nav className="container mx-auto flex justify-between items-center">
            <Image src={logo} alt="Logo dropit" width={100} height={50} />
            <div>
              <a href="#features" className="px-4">Features</a>
              <a href="#cta" className="px-4">Get Started</a>
            </div>
          </nav>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
