import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import logo from "/public/assets/logo.png";
import { Toaster } from "@/components/ui/sonner"
import HoverRippleButton from "@/components/hoverRippleButton";
import Link from "next/link";
import Copyright from "@/components/copyright";
import Script from "next/script";
import GoogleAnalyticsScript from "@/lib/analytics/googleAnalytics";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleAnalyticsScript />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="p-6">
          <nav className="flex justify-between items-center">
            <Link href="/"><Image src={logo} alt="Logo dropit" width={100} height={50} /></Link>
            <div className="flex gap-paragraph items-center">
              <Link href="/#features">Features</Link>
              <Link href="/#pricing">Pricing</Link>
              <HoverRippleButton className="rounded-none">Sign up</HoverRippleButton>
            </div>
          </nav>
        </header>
        <main className="flex-1">
          {children}
        </main>
        <footer className="bg-white p-8 w-full mt-16">
          <div className="flex justify-around">
            <div className="flex flex-col gap-title flex-2">
              <Image src={logo} alt="Logo dropit" height={80} />
              <p className="text-muted-foreground">
                Validate your business idea in 2 hours with market data<br />
                <Copyright />
              </p>
            </div>
            <div>
              <div className="text-lg font-bold mb-title">Legal</div>
              <ul className="space-y-1">
                <li><Link className="hover:underline" href="/legal/privacy">Privacy policy</Link></li>
                <li><Link className="hover:underline" href="/legal/cookies">Cookie policy</Link></li>
              </ul>
            </div>
          </div>
        </footer>
        <Toaster />
      </body>
    </html>
  );
}
